itemValues = {
    "Iron":                          1,
    "Explosives":                    2,
    "Hyper Rubber":                 25,
    "Flux Crystals":                10,
    "Volleyball":                 1000,
    "Golden Volleyball":        200000,
    "Basketball":                 1000,
    "Golden Basketball":        200000,
    "Beach Ball":                 1000,
    "Football":                   1000,
    "Golden Item Shredder":     200000,
    "Handheld Pusher":             320,
    "Backpack":                    250,
    "Speed Skates":                160,
    "Booster Boots":               160,
    "Launcher Gauntlets":          160,
    "Construction Gauntlets":      320,
    "Rocket Pack":                 320,
    "Hover Pack":                  320,
    "Manifest Scanner":            300,
    "BoM Scanner":                 300,
    "Blueprint Scanner":          5000,
    "Flux RCD":                   5000,
    "Bug Hunter Trophy":        200000,
    "Silver Null Trophy":       100000,
}